#!/usr/bin/env bash
set -euo pipefail

# DataForSEO Extension Installer for Claude SEO
# Wraps everything in main() to prevent partial execution on network failure

main() {
    SKILL_DIR="${HOME}/.claude/skills/seo-dataforseo"
    AGENT_DIR="${HOME}/.claude/agents"
    SEO_SKILL_DIR="${HOME}/.claude/skills/seo"
    # Pinned to major 3: v3 replaced the ~80 per-endpoint tools with api_request,
    # so a future major could break the skills the same way. Bump deliberately.
    DFSE_PACKAGE="dataforseo-mcp-server@3"

    echo "════════════════════════════════════════"
    echo "║   DataForSEO Extension - Installer   ║"
    echo "║   For Claude SEO                     ║"
    echo "════════════════════════════════════════"
    echo ""

    # Check prerequisites
    if [ ! -d "${SEO_SKILL_DIR}" ]; then
        echo "✗ Claude SEO is not installed."
        echo "  Install it first: curl -fsSL https://raw.githubusercontent.com/AgriciDaniel/claude-seo/main/install.sh | bash"
        exit 1
    fi
    echo "✓ Claude SEO detected"

    # dataforseo-mcp-server 3.1.x declares "engines": {"node": ">=22"} (npm registry)
    if ! command -v node >/dev/null 2>&1; then
        echo "✗ Node.js is required but not installed."
        echo "  Install Node.js 22+: https://nodejs.org/"
        exit 1
    fi

    NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
    if [ "${NODE_VERSION}" -lt 22 ]; then
        echo "✗ Node.js 22+ required by dataforseo-mcp-server 3.x (found v${NODE_VERSION})."
        echo "  Update: https://nodejs.org/"
        exit 1
    fi
    echo "✓ Node.js v$(node -v | sed 's/v//') detected"

    if ! command -v npx >/dev/null 2>&1; then
        echo "✗ npx is required but not found (comes with npm)."
        exit 1
    fi
    echo "✓ npx detected"

    # python3 runs the shared MCP registration helper (extensions/claude_mcp_config.py)
    if ! command -v python3 >/dev/null 2>&1; then
        echo "✗ python3 is required to register the MCP server."
        exit 1
    fi
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    MCP_HELPER=""
    for candidate in "${SCRIPT_DIR}/../claude_mcp_config.py" "${SCRIPT_DIR}/extensions/claude_mcp_config.py"; do
        if [ -f "${candidate}" ]; then MCP_HELPER="${candidate}"; break; fi
    done
    if [ -z "${MCP_HELPER}" ]; then
        echo "✗ Cannot find extensions/claude_mcp_config.py."
        echo "  Run this script from the claude-seo repo: ./extensions/dataforseo/install.sh"
        exit 1
    fi
    if command -v claude >/dev/null 2>&1; then
        echo "✓ claude CLI detected (MCP server will be added with: claude mcp add --scope user)"
    else
        echo "ℹ claude CLI not on PATH: the MCP server will be written to ~/.claude.json directly"
    fi

    # Prompt for credentials
    echo ""
    echo "DataForSEO API credentials required."
    echo "Sign up at: https://app.dataforseo.com/register"
    echo ""

    echo "Use the API login and API password from https://app.dataforseo.com/api-access"
    echo "(the API password is generated by DataForSEO and differs from your account password)."
    read -rp "DataForSEO API login: " DFSE_USERNAME
    if [ -z "${DFSE_USERNAME}" ]; then
        echo "✗ API login cannot be empty."
        exit 1
    fi

    read -rsp "DataForSEO API password: " DFSE_PASSWORD
    echo ""
    if [ -z "${DFSE_PASSWORD}" ]; then
        echo "✗ Password cannot be empty."
        exit 1
    fi

    # Check if running from repo or standalone
    if [ -f "${SCRIPT_DIR}/skills/seo-dataforseo/SKILL.md" ]; then
        SOURCE_DIR="${SCRIPT_DIR}"
    elif [ -f "${SCRIPT_DIR}/extensions/dataforseo/skills/seo-dataforseo/SKILL.md" ]; then
        SOURCE_DIR="${SCRIPT_DIR}/extensions/dataforseo"
    else
        echo "✗ Cannot find extension source files."
        echo "  Run this script from the claude-seo repo: ./extensions/dataforseo/install.sh"
        exit 1
    fi

    # Install skill
    echo ""
    echo "→ Installing DataForSEO skill..."
    mkdir -p "${SKILL_DIR}"
    cp "${SOURCE_DIR}/skills/seo-dataforseo/SKILL.md" "${SKILL_DIR}/SKILL.md"
    if [ -d "${SOURCE_DIR}/skills/seo-dataforseo/references" ]; then
        mkdir -p "${SKILL_DIR}/references"
        cp "${SOURCE_DIR}/skills/seo-dataforseo/references/"*.md "${SKILL_DIR}/references/"
    fi

    # Install agent
    echo "→ Installing DataForSEO agent..."
    mkdir -p "${AGENT_DIR}"
    cp "${SOURCE_DIR}/agents/seo-dataforseo.md" "${AGENT_DIR}/seo-dataforseo.md"

    # Install field config
    echo "→ Installing field config..."
    cp "${SOURCE_DIR}/field-config.json" "${SEO_SKILL_DIR}/dataforseo-field-config.json"

    # Register the MCP server at user scope. Claude Code reads user-scope MCP
    # servers from ~/.claude.json (via `claude mcp add --scope user`), never
    # from ~/.claude/settings.json, where installers up to v1.8.1 wrote them.
    echo "→ Registering MCP server (user scope)..."
    FIELD_CONFIG_PATH="${SEO_SKILL_DIR}/dataforseo-field-config.json"

    # Credentials go to the helper through the environment only: never argv of
    # this shell, never string interpolation, never echoed.
    DATAFORSEO_LOGIN="${DFSE_USERNAME}" DATAFORSEO_PASSWORD="${DFSE_PASSWORD}" \
    FIELD_CONFIG_PATH="${FIELD_CONFIG_PATH}" \
    python3 "${MCP_HELPER}" install --name dataforseo \
        --env-keys DATAFORSEO_LOGIN,DATAFORSEO_PASSWORD,FIELD_CONFIG_PATH \
        --secret-keys DATAFORSEO_LOGIN,DATAFORSEO_PASSWORD \
        -- npx -y "${DFSE_PACKAGE}" || {
        echo "  ⚠  Could not register the MCP server automatically. Run:"
        echo "     claude mcp add --env DATAFORSEO_LOGIN=<login> --env DATAFORSEO_PASSWORD=<password> \\"
        echo "       --env FIELD_CONFIG_PATH=${FIELD_CONFIG_PATH} --transport stdio --scope user \\"
        echo "       dataforseo -- npx -y ${DFSE_PACKAGE}"
        echo "  See: extensions/dataforseo/docs/DATAFORSEO-SETUP.md"
    }
    unset DFSE_PASSWORD

    # Pre-warm npx package
    echo "→ Pre-downloading ${DFSE_PACKAGE}..."
    npx -y "${DFSE_PACKAGE}" --version >/dev/null 2>&1 || true

    echo ""
    echo "✓ DataForSEO extension installed successfully!"
    echo ""
    echo "Usage:"
    echo "  1. Start Claude Code:  claude"
    echo "  2. Run commands:"
    echo "     /seo dataforseo serp best coffee shops"
    echo "     /seo dataforseo keywords seo tools"
    echo "     /seo dataforseo backlinks example.com"
    echo "     /seo dataforseo ai-mentions your brand"
    echo ""
    echo "All commands: see extensions/dataforseo/README.md"
    echo "To uninstall: ./extensions/dataforseo/uninstall.sh"
}

main "$@"
