# DataForSEO Extension Installer for Claude SEO (Windows)
# PowerShell installation script

$ErrorActionPreference = "Stop"

Write-Host "════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "║   DataForSEO Extension - Installer   ║" -ForegroundColor Cyan
Write-Host "║   For Claude SEO                     ║" -ForegroundColor Cyan
Write-Host "════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Check prerequisites
$SeoSkillDir = "$env:USERPROFILE\.claude\skills\seo"
if (-not (Test-Path $SeoSkillDir)) {
    Write-Host "✗ Claude SEO is not installed." -ForegroundColor Red
    Write-Host "  Install it first: irm https://raw.githubusercontent.com/AgriciDaniel/claude-seo/main/install.ps1 | iex"
    exit 1
}
Write-Host "✓ Claude SEO detected" -ForegroundColor Green

# Pinned to major 3: v3 replaced the per-endpoint tools with api_request,
# so a future major could break the skills the same way. Bump deliberately.
$DfsePackage = "dataforseo-mcp-server@3"

# dataforseo-mcp-server 3.1.x declares "engines": {"node": ">=22"} (npm registry)
$nodeCmd = Get-Command -Name node -ErrorAction SilentlyContinue
if ($null -eq $nodeCmd) {
    Write-Host "✗ Node.js is required but not installed." -ForegroundColor Red
    Write-Host "  Install Node.js 22+: https://nodejs.org/"
    exit 1
}

$nodeVersion = (node -v) -replace 'v','' -split '\.' | Select-Object -First 1
if ([int]$nodeVersion -lt 22) {
    Write-Host "✗ Node.js 22+ required by dataforseo-mcp-server 3.x (found v$nodeVersion)." -ForegroundColor Red
    exit 1
}
Write-Host "✓ Node.js $(node -v) detected" -ForegroundColor Green

$npxCmd = Get-Command -Name npx -ErrorAction SilentlyContinue
if ($null -eq $npxCmd) {
    Write-Host "✗ npx is required but not found (comes with npm)." -ForegroundColor Red
    exit 1
}
Write-Host "✓ npx detected" -ForegroundColor Green

# Prompt for credentials
Write-Host ""
Write-Host "DataForSEO API credentials required." -ForegroundColor Yellow
Write-Host "Sign up at: https://app.dataforseo.com/register"
Write-Host ""

Write-Host "Use the API login and API password from https://app.dataforseo.com/api-access"
Write-Host "(the API password is generated by DataForSEO and differs from your account password)."
$DfseUsername = Read-Host "DataForSEO API login"
if ([string]::IsNullOrEmpty($DfseUsername)) {
    Write-Host "✗ API login cannot be empty." -ForegroundColor Red
    exit 1
}

$DfsePasswordSecure = Read-Host "DataForSEO API password" -AsSecureString
$DfsePassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($DfsePasswordSecure)
)
if ([string]::IsNullOrEmpty($DfsePassword)) {
    Write-Host "✗ Password cannot be empty." -ForegroundColor Red
    exit 1
}

# Determine source directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (Test-Path "$ScriptDir\skills\seo-dataforseo\SKILL.md") {
    $SourceDir = $ScriptDir
} elseif (Test-Path "$ScriptDir\extensions\dataforseo\skills\seo-dataforseo\SKILL.md") {
    $SourceDir = "$ScriptDir\extensions\dataforseo"
} else {
    Write-Host "✗ Cannot find extension source files." -ForegroundColor Red
    Write-Host "  Run this script from the claude-seo repo."
    exit 1
}

# Set paths
$SkillDir = "$env:USERPROFILE\.claude\skills\seo-dataforseo"
$AgentDir = "$env:USERPROFILE\.claude\agents"
$SettingsFile = "$env:USERPROFILE\.claude\settings.json"
$FieldConfigPath = "$SeoSkillDir\dataforseo-field-config.json"

# Install skill
Write-Host ""
Write-Host "→ Installing DataForSEO skill..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path $SkillDir | Out-Null
Copy-Item -Force "$SourceDir\skills\seo-dataforseo\SKILL.md" "$SkillDir\SKILL.md"
if (Test-Path "$SourceDir\skills\seo-dataforseo\references") {
    New-Item -ItemType Directory -Force -Path "$SkillDir\references" | Out-Null
    Copy-Item -Force "$SourceDir\skills\seo-dataforseo\references\*.md" "$SkillDir\references\"
}

# Install agent
Write-Host "→ Installing DataForSEO agent..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path $AgentDir | Out-Null
Copy-Item -Force "$SourceDir\agents\seo-dataforseo.md" "$AgentDir\seo-dataforseo.md"

# Install field config
Write-Host "→ Installing field config..." -ForegroundColor Yellow
Copy-Item -Force "$SourceDir\field-config.json" $FieldConfigPath

# Merge MCP config into settings.json
Write-Host "→ Configuring MCP server..." -ForegroundColor Yellow

$python = Get-Command -Name python -ErrorAction SilentlyContinue
if ($null -eq $python) {
    $python = Get-Command -Name py -ErrorAction SilentlyContinue
}

if ($null -ne $python) {
    $pyExe = $python.Source
    $pyScript = @"
import json, os
settings_path = os.environ['DFSE_SETTINGS_FILE']
if os.path.exists(settings_path):
    with open(settings_path, 'r') as f:
        settings = json.load(f)
else:
    settings = {}
if 'mcpServers' not in settings:
    settings['mcpServers'] = {}
# v3: DATAFORSEO_LOGIN; ENABLED_MODULES no longer exists
settings['mcpServers']['dataforseo'] = {
    'command': 'npx',
    'args': ['-y', os.environ['DFSE_PACKAGE']],
    'env': {
        'DATAFORSEO_LOGIN': os.environ['DFSE_LOGIN'],
        'DATAFORSEO_PASSWORD': os.environ['DFSE_PASS'],
        'FIELD_CONFIG_PATH': os.environ['DFSE_FIELD_CONFIG']
    }
}
os.makedirs(os.path.dirname(settings_path), exist_ok=True)
with open(settings_path, 'w') as f:
    json.dump(settings, f, indent=2)
print('  ok')
"@

    # Credentials go through the environment, not string interpolation, so quotes
    # in the password cannot break the Python snippet.
    $env:DFSE_SETTINGS_FILE = $SettingsFile
    $env:DFSE_FIELD_CONFIG = $FieldConfigPath
    $env:DFSE_LOGIN = $DfseUsername
    $env:DFSE_PASS = $DfsePassword
    $env:DFSE_PACKAGE = $DfsePackage
    $result = & $pyExe -c $pyScript 2>&1
    Remove-Item Env:DFSE_PASS, Env:DFSE_LOGIN -ErrorAction SilentlyContinue
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  ✓ MCP server configured in settings.json" -ForegroundColor Green
    } else {
        Write-Host "  ⚠  Could not auto-configure MCP server." -ForegroundColor Yellow
        Write-Host "  Add the dataforseo server manually to ~\.claude\settings.json"
    }
} else {
    Write-Host "  ⚠  Python not found. Configure MCP server manually." -ForegroundColor Yellow
    Write-Host "  See: extensions\dataforseo\docs\DATAFORSEO-SETUP.md"
}

# Pre-warm npx package
Write-Host "→ Pre-downloading $DfsePackage..." -ForegroundColor Yellow
try {
    & npx -y $DfsePackage --version 2>&1 | Out-Null
} catch {
    # Ignore errors from pre-warm
}

Write-Host ""
Write-Host "✓ DataForSEO extension installed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Usage:" -ForegroundColor Cyan
Write-Host "  1. Start Claude Code:  claude"
Write-Host "  2. Run commands:"
Write-Host "     /seo dataforseo serp best coffee shops"
Write-Host "     /seo dataforseo keywords seo tools"
Write-Host "     /seo dataforseo backlinks example.com"
Write-Host "     /seo dataforseo ai-mentions your brand"
Write-Host ""
Write-Host "All commands: see extensions\dataforseo\README.md"
Write-Host "To uninstall: .\extensions\dataforseo\uninstall.ps1"
