# DataForSEO Extension Installer for Claude SEO (Windows)
# PowerShell installation script

$ErrorActionPreference = "Stop"

Write-Host "════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "║   DataForSEO Extension - Installer   ║" -ForegroundColor Cyan
Write-Host "║   For Claude SEO                     ║" -ForegroundColor Cyan
Write-Host "════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Check prerequisites
$SeoSkillDir = "$env:USERPROFILE\.claude\skills\seo"
if (-not (Test-Path $SeoSkillDir)) {
    Write-Host "✗ Claude SEO is not installed." -ForegroundColor Red
    Write-Host "  Install it first: irm https://raw.githubusercontent.com/AgriciDaniel/claude-seo/main/install.ps1 | iex"
    exit 1
}
Write-Host "✓ Claude SEO detected" -ForegroundColor Green

# Pinned to major 3: v3 replaced the per-endpoint tools with api_request,
# so a future major could break the skills the same way. Bump deliberately.
$DfsePackage = "dataforseo-mcp-server@3"

# dataforseo-mcp-server 3.1.x declares "engines": {"node": ">=22"} (npm registry)
$nodeCmd = Get-Command -Name node -ErrorAction SilentlyContinue
if ($null -eq $nodeCmd) {
    Write-Host "✗ Node.js is required but not installed." -ForegroundColor Red
    Write-Host "  Install Node.js 22+: https://nodejs.org/"
    exit 1
}

$nodeVersion = (node -v) -replace 'v','' -split '\.' | Select-Object -First 1
if ([int]$nodeVersion -lt 22) {
    Write-Host "✗ Node.js 22+ required by dataforseo-mcp-server 3.x (found v$nodeVersion)." -ForegroundColor Red
    exit 1
}
Write-Host "✓ Node.js $(node -v) detected" -ForegroundColor Green

$npxCmd = Get-Command -Name npx -ErrorAction SilentlyContinue
if ($null -eq $npxCmd) {
    Write-Host "✗ npx is required but not found (comes with npm)." -ForegroundColor Red
    exit 1
}
Write-Host "✓ npx detected" -ForegroundColor Green

# Shared MCP registration helper (extensions/claude_mcp_config.py). It runs
# `claude mcp add --scope user` (user-scope servers live in ~/.claude.json;
# Claude Code never reads mcpServers from ~/.claude/settings.json, where
# installers up to v1.8.1 wrote them), falls back to a JSON-safe merge into
# ~/.claude.json, and removes the legacy settings.json entry (backup first).
function Find-Python {
    foreach ($name in @('python3', 'python', 'py')) {
        $cmd = Get-Command -Name $name -CommandType Application -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if ($null -eq $cmd) { continue }
        $pre = @()
        if ($name -eq 'py') { $pre = @('-3') }
        try {
            # Skips the Microsoft Store "python" alias, which exits non-zero.
            & $cmd.Source @pre -c "import sys; sys.exit(0 if sys.version_info >= (3, 7) else 1)" 2>$null | Out-Null
            if ($LASTEXITCODE -eq 0) { return [pscustomobject]@{ Exe = $cmd.Source; Pre = $pre } }
        } catch { }
    }
    return $null
}

function Find-McpHelper([string]$Dir) {
    foreach ($candidate in @((Join-Path $Dir '..\claude_mcp_config.py'), (Join-Path $Dir 'extensions\claude_mcp_config.py'))) {
        if (Test-Path $candidate) { return (Resolve-Path $candidate).Path }
    }
    return $null
}

# Prompt for credentials
Write-Host ""
Write-Host "DataForSEO API credentials required." -ForegroundColor Yellow
Write-Host "Sign up at: https://app.dataforseo.com/register"
Write-Host ""

Write-Host "Use the API login and API password from https://app.dataforseo.com/api-access"
Write-Host "(the API password is generated by DataForSEO and differs from your account password)."
$DfseUsername = Read-Host "DataForSEO API login"
if ([string]::IsNullOrEmpty($DfseUsername)) {
    Write-Host "✗ API login cannot be empty." -ForegroundColor Red
    exit 1
}

$DfsePasswordSecure = Read-Host "DataForSEO API password" -AsSecureString
$DfsePassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($DfsePasswordSecure)
)
if ([string]::IsNullOrEmpty($DfsePassword)) {
    Write-Host "✗ Password cannot be empty." -ForegroundColor Red
    exit 1
}

# Determine source directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (Test-Path "$ScriptDir\skills\seo-dataforseo\SKILL.md") {
    $SourceDir = $ScriptDir
} elseif (Test-Path "$ScriptDir\extensions\dataforseo\skills\seo-dataforseo\SKILL.md") {
    $SourceDir = "$ScriptDir\extensions\dataforseo"
} else {
    Write-Host "✗ Cannot find extension source files." -ForegroundColor Red
    Write-Host "  Run this script from the claude-seo repo."
    exit 1
}

# Set paths
$SkillDir = "$env:USERPROFILE\.claude\skills\seo-dataforseo"
$AgentDir = "$env:USERPROFILE\.claude\agents"
$FieldConfigPath = "$SeoSkillDir\dataforseo-field-config.json"

# Install skill
Write-Host ""
Write-Host "→ Installing DataForSEO skill..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path $SkillDir | Out-Null
Copy-Item -Force "$SourceDir\skills\seo-dataforseo\SKILL.md" "$SkillDir\SKILL.md"
if (Test-Path "$SourceDir\skills\seo-dataforseo\references") {
    New-Item -ItemType Directory -Force -Path "$SkillDir\references" | Out-Null
    Copy-Item -Force "$SourceDir\skills\seo-dataforseo\references\*.md" "$SkillDir\references\"
}

# Install agent
Write-Host "→ Installing DataForSEO agent..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path $AgentDir | Out-Null
Copy-Item -Force "$SourceDir\agents\seo-dataforseo.md" "$AgentDir\seo-dataforseo.md"

# Install field config
Write-Host "→ Installing field config..." -ForegroundColor Yellow
Copy-Item -Force "$SourceDir\field-config.json" $FieldConfigPath

# Register the MCP server at user scope
Write-Host "→ Registering MCP server (user scope)..." -ForegroundColor Yellow
$python = Find-Python
$mcpHelper = Find-McpHelper $ScriptDir
$registered = $false
if ($null -ne $python -and $null -ne $mcpHelper) {
    # Credentials reach the helper through the environment only (never argv,
    # never string interpolation into code, never echoed). Splatting keeps the
    # literal '--' separator intact for the native command.
    $env:DATAFORSEO_LOGIN = $DfseUsername
    $env:DATAFORSEO_PASSWORD = $DfsePassword
    $env:FIELD_CONFIG_PATH = $FieldConfigPath
    $helperArgs = @($python.Pre) + @($mcpHelper, 'install', '--name', 'dataforseo',
        '--env-keys', 'DATAFORSEO_LOGIN,DATAFORSEO_PASSWORD,FIELD_CONFIG_PATH',
        '--secret-keys', 'DATAFORSEO_LOGIN,DATAFORSEO_PASSWORD',
        '--', 'npx', '-y', $DfsePackage)
    try {
        & $python.Exe @helperArgs
        $registered = ($LASTEXITCODE -eq 0)
    } catch {
        $registered = $false
    } finally {
        Remove-Item Env:DATAFORSEO_LOGIN, Env:DATAFORSEO_PASSWORD, Env:FIELD_CONFIG_PATH -ErrorAction SilentlyContinue
    }
} elseif ($null -eq $python) {
    Write-Host "  ⚠  Python 3 not found; cannot register the MCP server automatically." -ForegroundColor Yellow
} else {
    Write-Host "  ⚠  extensions\claude_mcp_config.py not found (run from the claude-seo repo)." -ForegroundColor Yellow
}
if (-not $registered) {
    Write-Host "  Register it yourself (replace the <...> values):"
    Write-Host "    claude mcp add --env DATAFORSEO_LOGIN=<login> --env DATAFORSEO_PASSWORD=<password> ``"
    Write-Host "      --env FIELD_CONFIG_PATH=$FieldConfigPath --transport stdio --scope user ``"
    Write-Host "      dataforseo -- npx -y $DfsePackage"
    Write-Host "  and delete any mcpServers.dataforseo entry from ~\.claude\settings.json."
    Write-Host "  See: extensions\dataforseo\docs\DATAFORSEO-SETUP.md"
}
$DfsePassword = $null

# Pre-warm npx package
Write-Host "→ Pre-downloading $DfsePackage..." -ForegroundColor Yellow
try {
    & npx -y $DfsePackage --version 2>&1 | Out-Null
} catch {
    # Ignore errors from pre-warm
}

Write-Host ""
Write-Host "✓ DataForSEO extension installed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Usage:" -ForegroundColor Cyan
Write-Host "  1. Start Claude Code:  claude"
Write-Host "  2. Run commands:"
Write-Host "     /seo dataforseo serp best coffee shops"
Write-Host "     /seo dataforseo keywords seo tools"
Write-Host "     /seo dataforseo backlinks example.com"
Write-Host "     /seo dataforseo ai-mentions your brand"
Write-Host ""
Write-Host "All commands: see extensions\dataforseo\README.md"
Write-Host "To uninstall: .\extensions\dataforseo\uninstall.ps1"
